### PR TITLE
full request test

### PR DESCRIPTION
**Pull request by hlpss891092002**
full request test
fiexd to FastAPI

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
You should add protection rules on 'main' branch.
Re-request review after you fix this issue.

**Comment by hlpss891092002** [comment]
I added the  protection rules on main branch.
Please confirm  the change.

**Comment by cwpeng** [comment]
Re-request review explicitly from top-right corner in this page, so that I can review for you.

**Comment by hlpss891092002** [comment]
Thank you for leading me to request!

**Review by cwpeng — APPROVED** [review]
OK.

**Pull request merged**
